"""agentsbridge CLI - bridge AGENTS.md to every AI coding tool's rules file."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import __version__, core


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="agentsbridge",
        description=(
            "Bridge AGENTS.md to every AI coding tool's rules file. "
            "Maintain one source of truth; generate CLAUDE.md, "
            "copilot-instructions.md, Cursor rules, and more."
        ),
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="command")

    p_sync = sub.add_parser("sync", help="generate all target rules files from AGENTS.md")
    p_sync.add_argument(
        "-t",
        "--targets",
        default="",
        help="comma-separated subset of targets (default: all)",
    )
    p_sync.add_argument(
        "--force", action="store_true", help="overwrite files not generated by agentsbridge"
    )
    p_sync.add_argument(
        "--dry-run", action="store_true", help="show what would change without writing"
    )

    p_check = sub.add_parser(
        "check", help="exit non-zero if any generated file drifted from AGENTS.md (for CI)"
    )
    p_check.add_argument(
        "-t",
        "--targets",
        default="",
        help="comma-separated subset of targets (default: all)",
    )

    p_import = sub.add_parser(
        "import", help="seed AGENTS.md from an existing rules file (CLAUDE.md, .cursorrules, ...)"
    )
    p_import.add_argument("--out", default="AGENTS.md", help="output path (default: AGENTS.md)")

    p_init = sub.add_parser("init", help="create a starter AGENTS.md")
    p_init.add_argument("--force", action="store_true", help="overwrite existing AGENTS.md")

    sub.add_parser(
        "list",
        help="list all supported targets and the files they generate",
    )

    return parser


def _parse_targets(value: str) -> list[str] | None:
    value = value.strip()
    if not value:
        return None
    return [v.strip() for v in value.split(",") if v.strip()]


def _root() -> Path:
    return Path.cwd()


def cmd_sync(args: argparse.Namespace) -> int:
    root = core.walk_up(_root())
    try:
        results = core.sync(
            root, _parse_targets(args.targets), force=args.force, dry_run=args.dry_run
        )
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    label = "would create/update" if args.dry_run else "wrote"
    for r in results:
        icon = {
            "created": "+",
            "updated": "~",
            "unchanged": "=",
            "skipped": "!",
            "missing": "?",
        }.get(r.action, " ")
        detail = f"  ({r.detail})" if r.detail else ""
        print(f"  {icon} {r.action:<9} {core.relative_display(r.path, root)}{detail}")
    created = sum(1 for r in results if r.action in ("created", "updated"))
    skipped = sum(1 for r in results if r.action == "skipped")
    print(
        f"\n{label} {created} file(s)"
        + (f", skipped {skipped}" if skipped else "")
        + (" (dry run)" if args.dry_run else "")
    )
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    root = core.walk_up(_root())
    try:
        clean, results = core.check(root, _parse_targets(args.targets))
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    for r in results:
        icon = {"ok": "=", "drifted": "!", "missing": "?", "skipped": "-"}.get(r.action, " ")
        detail = f"  ({r.detail})" if r.detail else ""
        print(f"  {icon} {r.action:<9} {core.relative_display(r.path, root)}{detail}")
    if clean:
        print("\nall target files are up to date")
        return 0
    counts: dict[str, int] = {}
    for r in results:
        counts[r.action] = counts.get(r.action, 0) + 1
    summary = ", ".join(f"{v} {k}" for k, v in sorted(counts.items()) if k != "ok")
    print(f"\ndrift detected ({summary}): run `agentsbridge sync` to fix", file=sys.stderr)
    return 1


def cmd_import(args: argparse.Namespace) -> int:
    root = _root()
    try:
        body, src = core.import_source(root)
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    out_path = root / args.out
    if out_path.exists():
        print(f"error: {out_path} already exists. Delete it first or use --out.", file=sys.stderr)
        return 1
    out_path.write_text(body.rstrip() + "\n", encoding="utf-8")
    print(f"created {out_path} from {src.name}")
    print("review it, then run `agentsbridge sync` to propagate.")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    root = _root()
    if (root / core.SOURCE_FILENAME).exists() and not args.force:
        print("AGENTS.md already exists (use --force to overwrite)")
        return 0
    r = core.ensure_agents_md(root, dry_run=False)
    if r.action == "created":
        print(f"created {r.path}")
        print("edit it, then run `agentsbridge sync`")
    return 0


def cmd_list(args: argparse.Namespace) -> int:
    del args  # unused; kept for uniform command signature
    from .targets import NATIVE_TOOLS, TARGETS

    name_width = max(len(t.name) for t in TARGETS.values())
    for t in sorted(TARGETS.values(), key=lambda t: t.name):
        print(f"  {t.name:<{name_width}}  {t.path:<36} {t.description}")
    print(f"\n  {'(native)':<{name_width}}  read AGENTS.md directly, nothing generated:")
    print("    " + ", ".join(NATIVE_TOOLS))
    return 0


COMMANDS = {
    "sync": cmd_sync,
    "check": cmd_check,
    "import": cmd_import,
    "init": cmd_init,
    "list": cmd_list,
}


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not args.command:
        parser.print_help()
        return 0
    return COMMANDS[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
