"""Core logic: parse AGENTS.md, render targets, sync/check/import/init."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from .targets import GENERATED_MARKER, TARGETS, Target, render

SOURCE_FILENAME = "AGENTS.md"

# Files agentsbridge knows how to import from, in priority order.
IMPORT_SOURCES = [
    "CLAUDE.md",
    ".github/copilot-instructions.md",
    ".cursorrules",
    ".clinerules",
    ".windsurfrules",
    "CONVENTIONS.md",
]


@dataclass
class SyncResult:
    target: str
    path: Path
    action: str  # created | updated | skipped | unchanged
    detail: str = ""


def find_source(root: Path) -> Path | None:
    p = root / SOURCE_FILENAME
    return p if p.is_file() else None


def read_source(root: Path) -> str:
    p = find_source(root)
    if p is None:
        raise FileNotFoundError(
            f"No {SOURCE_FILENAME} found in {root}. Run `agentsbridge init` first."
        )
    return strip_generated_marker(p.read_text(encoding="utf-8"))


def strip_generated_marker(text: str) -> str:
    """Remove our own marker so re-importing a generated file stays clean."""
    lines = text.splitlines()
    out = [ln for ln in lines if GENERATED_MARKER not in ln]
    return "\n".join(out).strip()


def is_generated(path: Path) -> bool:
    try:
        return GENERATED_MARKER in path.read_text(encoding="utf-8", errors="replace")[:500]
    except OSError:
        return False


def sync(
    root: Path,
    selected: list[str] | None = None,
    force: bool = False,
    dry_run: bool = False,
) -> list[SyncResult]:
    """Generate target files from AGENTS.md."""
    body = read_source(root)
    targets = resolve_targets(selected)
    results: list[SyncResult] = []

    for target in targets:
        path = root / target.path
        content = render(target, body)

        if path.exists():
            if not force and not is_generated(path):
                results.append(
                    SyncResult(
                        target.name,
                        path,
                        "skipped",
                        "file exists and was not generated by agentsbridge (use --force to overwrite)",
                    )
                )
                continue
            if path.read_text(encoding="utf-8", errors="replace") == content:
                results.append(SyncResult(target.name, path, "unchanged"))
                continue
            action = "updated"
        else:
            action = "created"

        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        results.append(SyncResult(target.name, path, action))

    return results


def check(root: Path, selected: list[str] | None = None) -> tuple[bool, list[SyncResult]]:
    """Return (clean, results). clean=False means at least one target drifted."""
    body = read_source(root)
    targets = resolve_targets(selected)
    results: list[SyncResult] = []
    clean = True

    for target in targets:
        path = root / target.path
        content = render(target, body)

        if not path.exists():
            clean = False
            results.append(SyncResult(target.name, path, "missing"))
            continue
        if not is_generated(path):
            # Hand-written file: we never claim drift on files we don't own.
            results.append(SyncResult(target.name, path, "skipped", "not generated"))
            continue
        if path.read_text(encoding="utf-8", errors="replace") != content:
            clean = False
            results.append(SyncResult(target.name, path, "drifted"))
        else:
            results.append(SyncResult(target.name, path, "ok"))

    return clean, results


def resolve_targets(selected: list[str] | None) -> list[Target]:
    if not selected:
        return list(TARGETS.values())
    unknown = [s for s in selected if s not in TARGETS]
    if unknown:
        raise ValueError(
            f"Unknown target(s): {', '.join(unknown)}. Available: {', '.join(sorted(TARGETS))}"
        )
    # preserve user order, dedupe
    seen: set[str] = set()
    out = []
    for s in selected:
        if s not in seen:
            seen.add(s)
            out.append(TARGETS[s])
    return out


def import_source(root: Path) -> tuple[str, Path]:
    """Find an existing rules file and return (body, path) to seed AGENTS.md."""
    for name in IMPORT_SOURCES:
        p = root / name
        if p.is_file():
            text = p.read_text(encoding="utf-8", errors="replace")
            return strip_generated_marker(text), p
    raise FileNotFoundError(
        "No importable rules file found. Looked for: " + ", ".join(IMPORT_SOURCES)
    )


def init_template() -> str:
    return """# Coding Agent Rules

<!-- Edit this file. Run `agentsbridge sync` to propagate changes to
     CLAUDE.md, .github/copilot-instructions.md, Cursor, Windsurf, Cline,
     Aider, and more. Tools that read AGENTS.md natively (Codex CLI,
     Gemini CLI, Jules, Amp, Zed) need no bridging. -->

## General

- Write clear, idiomatic code; prefer simplicity over cleverness.
- Keep functions small and focused; extract helpers when logic repeats.

## Testing

- Add or update tests for every behavior change.
- Run the test suite before committing.

## Git

- Commit messages: imperative mood, under 72 characters.
- One logical change per commit.
"""


def ensure_agents_md(root: Path, template: str | None = None, dry_run: bool = False) -> SyncResult:
    path = root / SOURCE_FILENAME
    if path.exists():
        return SyncResult("agents", path, "unchanged", "AGENTS.md already exists")
    content = template if template is not None else init_template()
    if not dry_run:
        path.write_text(content, encoding="utf-8")
    return SyncResult("agents", path, "created")


def walk_up(start: Path) -> Path:
    """Walk up from start to find the nearest directory containing AGENTS.md."""
    cur = start.resolve()
    for p in [cur, *cur.parents]:
        if (p / SOURCE_FILENAME).is_file():
            return p
    return start.resolve()


def is_quiet() -> bool:
    return os.environ.get("AGENTSBRIDGE_QUIET") == "1"
