"""Target definitions: how AGENTS.md content maps to each tool's rules file.

A target is a callable-free dataclass describing:
  - name: identifier used on the CLI (--targets claude,copilot)
  - path: file path relative to the project root
  - style: how the body should be rendered (raw markdown, mdc frontmatter, ...)
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Target:
    name: str
    path: str
    style: str = "markdown"  # markdown | mdc
    description: str = ""
    # Some tools nest rules in subdirectories; record parent dirs to create.
    extra_dirs: tuple[str, ...] = field(default_factory=tuple)


TARGETS: dict[str, Target] = {
    t.name: t
    for t in [
        Target(
            name="claude",
            path="CLAUDE.md",
            style="markdown",
            description="Claude Code (project memory)",
        ),
        Target(
            name="copilot",
            path=".github/copilot-instructions.md",
            style="markdown",
            description="GitHub Copilot",
        ),
        Target(
            name="cursor",
            path=".cursor/rules/agentsbridge.mdc",
            style="mdc",
            description="Cursor (rules dir)",
        ),
        Target(
            name="windsurf",
            path=".windsurfrules",
            style="markdown",
            description="Windsurf",
        ),
        Target(
            name="cline",
            path=".clinerules",
            style="markdown",
            description="Cline",
        ),
        Target(
            name="aider",
            path="CONVENTIONS.md",
            style="markdown",
            description="Aider",
        ),
        Target(
            name="roo",
            path=".roo/rules/agentsbridge.md",
            style="markdown",
            description="Roo Code / Zoo Code (rules dir)",
            extra_dirs=(".roo/rules",),
        ),
        Target(
            name="kilocode",
            path=".kilocode/rules/agentsbridge.md",
            style="markdown",
            description="Kilo Code (rules dir)",
            extra_dirs=(".kilocode/rules",),
        ),
        Target(
            name="junie",
            path=".junie/guidelines.md",
            style="markdown",
            description="JetBrains Junie",
            extra_dirs=(".junie",),
        ),
        Target(
            name="amazonq",
            path=".amazonq/rules/agentsbridge.md",
            style="markdown",
            description="Amazon Q Developer (rules dir)",
            extra_dirs=(".amazonq/rules",),
        ),
        Target(
            name="gemini",
            path="GEMINI.md",
            style="markdown",
            description="Gemini CLI (legacy GEMINI.md)",
        ),
    ]
}

# Tools that read AGENTS.md natively - no bridging needed, documented only.
NATIVE_TOOLS = [
    "Codex CLI",
    "Gemini CLI (recent versions)",
    "Jules",
    "Amp",
    "Zed",
    "Cursor (newer versions)",
    "Factory Droids",
    "opencode",
]

GENERATED_MARKER = "<!-- generated by agentsbridge; do not edit -->"


def render(target: Target, body: str) -> str:
    """Render the AGENTS.md body for a specific target style."""
    if target.style == "mdc":
        return _render_mdc(body)
    return _render_markdown(body)


def _render_markdown(body: str) -> str:
    lines = [
        GENERATED_MARKER,
        "",
        "> Generated from `AGENTS.md` by [agentsbridge](https://github.com/DavidStarYu/agentsbridge).",
        "> Run `agentsbridge sync` after editing `AGENTS.md`. Do not edit this file directly.",
        "",
        body.rstrip(),
        "",
    ]
    return "\n".join(lines)


def _render_mdc(body: str) -> str:
    lines = [
        "---",
        "description: Coding agent rules generated from AGENTS.md by agentsbridge",
        "globs: **/*",
        "alwaysApply: true",
        "---",
        "",
        GENERATED_MARKER,
        "",
        "> Generated from `AGENTS.md` by [agentsbridge](https://github.com/DavidStarYu/agentsbridge).",
        "> Run `agentsbridge sync` after editing `AGENTS.md`. Do not edit this file directly.",
        "",
        body.rstrip(),
        "",
    ]
    return "\n".join(lines)
